//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMath.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class DUE
    {
        public int DUES_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string VOUCHER_NO { get; set; }
        public Nullable<int> VENDOR_FID { get; set; }
        public Nullable<int> USER_FID { get; set; }
        public Nullable<int> HEAD_FID { get; set; }
        public Nullable<int> MODES_OF_PAYMENTS_FID { get; set; }
        public Nullable<decimal> EXPENSE_AMOUNT { get; set; }
        public Nullable<decimal> INCOME_AMOUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public string PIC { get; set; }
        public int DISTYPE_FID { get; set; }
        public string DUESTYPE { get; set; }
        public string exp_type { get; set; }
        public HttpPostedFileBase due_photo { get; set; }
    
        public virtual DISTYPE DISTYPE { get; set; }
        public virtual HEAD HEAD { get; set; }
        public virtual MODES_OF_PAYMENTS MODES_OF_PAYMENTS { get; set; }
        public virtual USER USER { get; set; }
        public virtual VENDOR VENDOR { get; set; }

    }
}
