//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMath.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.SALARies = new HashSet<SALARY>();
            this.USERS = new HashSet<USER>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_CONTACT { get; set; }
        public string EMPLOYEE_EMAIL { get; set; }
        public string EMPLOYEE_PHOTO { get; set; }
        public string EMPLOYEE_ADDRESS { get; set; }
        public string EMPLOYEE_CNIC { get; set; }
        public string EMPLOYEE_DESIGNATION { get; set; }
        public Nullable<decimal> EMPLOYEE_MONTHLY_SALARY { get; set; }
        public string EMPLOYEE_DESCRIPTION { get; set; }
        public bool IsActive { get; set; }
        public string EMPLOYEE_TYPE { get; set; }
        public string EMPLOYEE_ALLOWENCES { get; set; }
        public HttpPostedFileBase emp_photo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALARY> SALARies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
    }
}
