//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMath.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbmathEntities : DbContext
    {
        public dbmathEntities()
            : base("name=dbmathEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SALARY> SALARies { get; set; }
        public virtual DbSet<DISHEAD> DISHEADS { get; set; }
        public virtual DbSet<DISTYPE> DISTYPEs { get; set; }
        public virtual DbSet<DUE> DUES { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual DbSet<FINANCIALYEAR> FINANCIALYEARS { get; set; }
        public virtual DbSet<HEAD> HEADS { get; set; }
        public virtual DbSet<HEADTYPE> HEADTYPES { get; set; }
        public virtual DbSet<MODES_OF_PAYMENTS> MODES_OF_PAYMENTS { get; set; }
        public virtual DbSet<PATIENT_INFO> PATIENT_INFO { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERTYPE> USERTYPES { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
    }
}
