//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMath.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT_INFO
    {
        public int PATIENT_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string NAME { get; set; }
        public string FATHER_NAME { get; set; }

        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> DATE_OF_ADDMISSION { get; set; }
        public Nullable<System.DateTime> DATE_OF_DISCHARGE { get; set; }
        public string MONTH { get; set; }
        public string CONTACT { get; set; }
        public string CATEGORY { get; set; }
        public string AGE { get; set; }
        public string CITY { get; set; }
        public string ADDRESS { get; set; }
        public string RELIGION { get; set; }
        public string CHRONIC_MEDICAL_PROBLEM { get; set; }
        public string CMP_SPECIFY { get; set; }
        public string REGULARLY_TAKING_OR_SHOULD_BE_TAKING_PRESCRIBED_MEDICATION { get; set; }
        public string EDUCATION { get; set; }
        public string OCCUPATION { get; set; }
        public string DRUG_TYPE { get; set; }
        public string R_O_A { get; set; }
        public string REASON_FOR_SUBSTANCE_USE { get; set; }
        public string HOW_MANY_TIMES_BEFORE_TREATED_FOR_SUBSTANCE_USE { get; set; }
        public string REASON_BEHIND_RELAPSE { get; set; }
        public string HAVING_EVER_BEEN_ARRESTED_AND_CHARGED_FOR_ANY_CRIME { get; set; }
        public string HC_SPECIFY { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string LIVES_WITH_ANY_ONE_WHO_ABUSES_DRUGS_ALCOHAL { get; set; }
        public string LDA_SPECIFIER { get; set; }
        public string YOU_HAD_EXPERIENCED_SERIOUS_PROBLEM_WITH_YOUR_FAMILY_OTHER_SIGNIFICANT_FAMILY { get; set; }
        public string SF_SPECIFY { get; set; }
        public string HAS_ANY_ONE_ABUSED_YOU { get; set; }
        public string EXPERIENCED_SERIOUS_DEPRESSION_MOOD_SWINGS_WHICH_INTERFARE_WITH_LIFE { get; set; }
        public string EXPERIENCED_SERIOUS_ANXIOUSNESS_OR_TENSE_ANXIETY_OR_PANIC_ATTACKS { get; set; }
        public string EXPERIENCES_TROUBLE_CONCENTRATING_UNDERSTANDING_REMEMBERING_VISUAL_OR_AUDIO_HALLUCINATIONS { get; set; }
        public string TEMPER_OR_VIOLENT_BEHAVIOUR_CONTROL_PROBLEMS { get; set; }
        public string PLAN_TO_HURT_OR_KILL_SOMEONE { get; set; }
        public string SERIOUS_PLAN_FOR_KILLING_SELF { get; set; }
        public string SUCIDE_ATTEMPTS { get; set; }
        public Nullable<int> USER_FID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
