//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMath.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARY
    {
        public int EMPLOYEE_FID { get; set; }
        public string EXTRA_DUTY { get; set; }
        public string TOTAL_SALARY { get; set; }
        public string ADVANCE_AMOUNT { get; set; }
        public string ABSENT_DAYS { get; set; }
        public string BY_CHEQUE { get; set; }
        public string BY_CASH { get; set; }
        public string NET_SALARY { get; set; }
        public Nullable<System.DateTime> SALARY_DATE { get; set; }
        public string ABSENT_AMOUNT { get; set; }
        public int SALARY_ID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
