//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMath.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class VENDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDOR()
        {
            this.DUES = new HashSet<DUE>();
        }
    
        public int VENDOR_ID { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_PIC { get; set; }
        public string VENDOR_ADDRESS { get; set; }
        public string VENDOR_PHONE { get; set; }
        public string VENDOR_DESCRIPTION { get; set; }
        public bool isActive { get; set; }
        public HttpPostedFileBase vendor_photo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUE> DUES { get; set; }
    }
}
